// name은 원하는대로 작성
name: Clue Deploy

// 감지할 event : push, pull request
// develop에 push가 발생하므로 branch를 master가 아닌 develop으로 설정
on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - './**'
      - .github/workflows/deploy.yml

// root folder가 ./가 아닌 ./front 
// root가 ./ 라면 하단의 working-directory 모두 생략 가능
env:
  working-directory: ./

jobs:
  build:
  // 작업이 수행될 환경 : 최신 우분투 서버
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ${{ env.working-directory }}

      - name: Run build
        run: yarn run build
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
		// key와 secret key settings에서 추가
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-<span class="hljs-number">2

      - name: Upload to S3
        run: aws s3 cp --recursive --region ap-northeast-2 build
            s3://pick-place
        working-directory: ${{ env.working-directory }}</code>
